name: metaphor_beta
description: Messenger App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  #firebase_auth: ^0.14.0+5
  firebase_auth:
    git:
      url: https://github.com/collinjackson/plugins.git
      ref: 441417c2fed0ff26bf84a49ab2c5ffd2aa5487de
      path: packages/firebase_auth

  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.4
  cloud_firestore: ^0.12.9+2
  google_sign_in: ^4.0.7
  fluttertoast: ^3.1.2
  image_picker: ^0.6.1+4
  shared_preferences: ^0.5.3+4

  intl: ^0.16.0
  firebase_dynamic_links: ^0.5.0+1
  cached_network_image: ^1.1.1

  permission_handler: ^3.2.2
  country_code_picker: ^1.1.7
  flutter_sms: ^1.0.1
  flutter_linkify: ^2.1.0
  url_launcher: ^5.1.2
  photo_view: ^0.4.2
  share: ^0.6.2+1
  connectivity: ^0.4.4

  flutter_webrtc: ^0.1.7
  contacts_service: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/google_logo.jpg
    - images/google.png
    - images/img_not_available.jpeg
    - images/particles_dark.gif
    - images/club_2.jpg
    - images/rsz_club_2.png
    - images/abstract.png
    - images/abstract_2.png
    - images/navy_blue_1.jpg
    - images/navy_blue_2.jpg
    - images/navy_blue_2_1.png
    - images/navy_blue_3.jpg
    - images/navy_blue_4.jpg
    - images/navy_blue_5.jpg
    - images/navy_blue_6.jpg
    - emoji/1f621.png
    - emoji/1f607.png
    - emoji/1f642.png
    - emoji/1f643.png
    - emoji/1f609.png
    - emoji/1f604.png
    - emoji/1f606.png
    - emoji/1f605.png
    - emoji/1f602.png
    - emoji/1f923.png
    - emoji/1f60d.png
    - emoji/1f60b.png
    - emoji/1f61b.png
    - emoji/1f92a.png
    - emoji/1f9d0.png
    - emoji/1f60e.png
    - emoji/1f60f.png
    - emoji/1f613.png
    - emoji/1f914.png
    - emoji/1f97a.png
    - emoji/1f631.png
    - emoji/1f915.png
    - emoji/1f634.png
    - emoji/1f62d.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
